export const FETCH_FOREIGN_CURRENCY = 'FETCH/FOREIGN_CURRENCY'
export const FETCH_UA_CURRENCY = 'FETCH/UA_CURRENCY'

export const LOADER_HIDE = 'APP/LOADER_HIDE'
export const LOADER_SHOW = 'APP/LOADER_SHOW'
export const IS_ERROR_HIDE = 'APP/IS_ERROR_HIDE'
export const IS_ERROR_SHOW = 'APP/IS_ERROR_SHOW'

export const CHANGE_AMOUNT = 'FETCH/FOREIGN_CURRENCY'
