export const FETCH_FOREIGN_CURRENCY = 'FETCH/FOREIGN_CURRENCY'
export const FETCH_UA_CURRENCY = 'FETCH/UA_CURRENCY'
export const LOADER_SHOW_HIDE = 'LOADER/SHOW_OR_HIDE'

export const CHANGE_AMOUNT = 'FETCH/FOREIGN_CURRENCY'
